### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by getsync** [ericyonng/kcp_cpp#1]
使用 winsolution_build.bat 创建的vs2019的工程，无法编译

[output.txt](https://github.com/ericyonng/kcp_cpp/files/10441845/output.txt)

**Comment by getsync** [comment]
vs2022中需要将源代码编码批量修改为GB2312,即可通过编译

**Comment by ericyonng** [comment]
> 使用 winsolution_build.bat 创建的vs2019的工程，无法编译
> 
> [output.txt](https://github.com/ericyonng/kcp_cpp/files/10441845/output.txt)

![image](https://user-images.githubusercontent.com/29380301/213336635-897dd6d5-136f-4d1e-b948-e00381b33559.png)
注意到了，runfirstly_scripts.bat脚本的LF => CRLF 即可，是这个脚本的问题，需要改成windows下的换行符即可，其他不需要动，谢谢反馈！！
